# Generated by Django 5.2.5 on 2025-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
